# -*- coding: utf-8 -*-
"""
/***************************************************************************
 latLonCalc
                                 A QGIS plugin
 tranform lon lat coordinates to DMS coordinates and vice versa


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-26
        copyright            : (C) 2023 by Khaled Hammami
        email                : hammami.khaled119@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load latLonCalc class from file latLonCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .latloncalc import latLonCalc
    return latLonCalc(iface)
